language: android
jdk: oraclejdk8
dist: focal
sudo: required
group: edge

android:
  components:
    - tools
    - android-29

install:
  - sudo apt-get install build-essential golang qemu qemu-kvm qemu-system qemu-system-x86 qemu-utils fdisk python3 python3-pip python3-setuptools dosfstools rpm2cpio libarchive-tools adb ffmpeg git
  - sudo pip3 install https://github.com/EtchDroid/qemu_test_orchestrator/archive/master.zip
  - yes | sdkmanager 'ndk-bundle'
  - yes | sdkmanager 'cmake;3.6.4111459'

env:
  global:
    - ADB_INSTALL_TIMEOUT=8
    - PYTHONUNBUFFERED=1
    - JOB_COMMAND="./gradlew androidtests:connectedAndroidTest"
    - VNC_RECORDER=1
    - VNC_RECORDER_BIN=/tmp/vnc-recorder/vnc-recorder
    - VNC_RECORDER_OUTPUT="$TRAVIS_BUILD_DIR/screenrec.mp4"
  matrix:
    # Note to readers: do not "fill the gaps": Android-x86 RPM images are not available for all versions.
    # Make sure new ones are added first to the download script and test them.
    - API=23 VIRTWIFI_HACK=0 API_NAME=marshmallow
    - API=25 VIRTWIFI_HACK=1 API_NAME=nougat
    - API=27 VIRTWIFI_HACK=1 API_NAME=oreo
    - API=28 VIRTWIFI_HACK=1 API_NAME=pie

before_script:
  # libusb
  - ls
  - wget https://github.com/libusb/libusb/archive/v1.0.23.zip
  - unzip v1.0.23.zip
  - echo "libusb.dir=$TRAVIS_BUILD_DIR/libusb-1.0.23" > $TRAVIS_BUILD_DIR/local.properties
  # vnc-recorder
  - pushd /tmp
  - git clone https://github.com/Depau/vnc-recorder.git --depth 1
  - cd vnc-recorder
  - go build
  - popd

script:
  - ./.ci_helpers/instrumented_tests_qemu.sh "$API"
  # TODO: Upload screen recording to Minio or somewhere

